#
# Clock-and-reset generator for the Colorlight i9plus + USB3300 ULPI setup.
# Single USB device, no audio PLL yet — that comes when we wire I2S or
# bring over the AVB stack.
#
# Clock domains:
#   sync : main fabric clock. clk25 × 12 ÷ 5 = 60 MHz from the on-board PLL.
#   usb  : 60 MHz sourced directly from ULPI_CLK (driven by the USB3300).
#   fast : 240 MHz, present because the LUNA USB stack derives some
#          DDR ULPI paths from it. Generated by the same PLL.
#
# When we add audio later, a second PLL can generate audio_clk from the
# main 25 MHz input — keeping that PLL separate from the USB one avoids
# coupling re-locks during MMCM DRP retuning of the audio rate.

from amaranth import Module, Elaboratable, ClockDomain, Signal, Instance, ResetSignal
from amaranth.lib.cdc import ResetSynchronizer


class ColorlightI9PlusCAR(Elaboratable):
    """Clock domain generator for Colorlight i9plus + USB3300 ULPI.

    The top-level Elaboratable requests both `ulpi` and `clk25`, then
    passes the ulpi.clk pin to this CAR's constructor. We can't
    `platform.request("ulpi", 0)` here because LUNA's USBDevice in the
    top-level requests it first.

    Used as `platform.clock_domain_generator(ulpi_clk_pin=...)` from
    the top-level. The kwargs match LUNA's calling convention plus our
    ulpi_clk_pin extension.
    """

    def __init__(self, *, ulpi_clk_pin=None, usb_phase=-120.0,
                 clock_frequencies=None, clock_signal_name=None):
        # LUNA passes clock_frequencies/clock_signal_name but we don't
        # use them; ulpi_clk_pin is OUR addition — the top-level provides
        # the already-requested ulpi.clk subsignal.
        self.ulpi_clk_pin = ulpi_clk_pin
        self.usb_phase    = usb_phase

    def elaborate(self, platform):
        m = Module()

        cd_sync = ClockDomain("sync")
        cd_usb  = ClockDomain("usb")
        cd_fast = ClockDomain("fast")
        m.domains += [cd_sync, cd_usb, cd_fast]

        clk25 = platform.request(platform.default_clk, 0)

        # --- Main PLL: clk25 → 60 MHz (sync) + 240 MHz (fast) ---
        # VCO = 25 × 24 = 600 MHz. clkout0 = 600/10 = 60 MHz. clkout1 = 600/2.5 = 240 MHz.
        # PLLE2_ADV is the Artix-7 PLL primitive (less capable than MMCM but
        # sufficient for our single VCO + two outputs).
        mainpll_feedback = Signal()
        sys_clk          = Signal()
        fast_clk         = Signal()
        sys_locked       = Signal()

        m.submodules.mainpll = Instance("PLLE2_ADV",
            p_BANDWIDTH       = "OPTIMIZED",
            # "INTERNAL" is what nextpnr-xilinx's fasm backend supports;
            # "ZHOLD" (Vivado default) crashes the open toolchain at
            # post-routing legalisation (fasm.cc:1572).
            p_COMPENSATION    = "INTERNAL",
            p_STARTUP_WAIT    = "FALSE",
            p_DIVCLK_DIVIDE   = 1,
            # VCO must be 800-1600 MHz on XC7A50T-1 (UG472). Previous
            # MULT=24 gave VCO=600 MHz — out of spec; PLL output was
            # undefined.  MULT=48 → VCO = 25 × 48 = 1200 MHz (well in
            # spec) gives clean integer dividers for 60 / 200 MHz.
            p_CLKFBOUT_MULT   = 48,
            p_CLKFBOUT_PHASE  = 0.0,
            p_CLKIN1_PERIOD   = 40.0,            # clk25 → 40 ns period

            p_CLKOUT0_DIVIDE  = 20,              # 1200 / 20 = 60 MHz (sync)
            p_CLKOUT0_PHASE   = 0.0,
            p_CLKOUT0_DUTY_CYCLE = 0.5,

            p_CLKOUT1_DIVIDE  = 6,               # 1200 / 6 = 200 MHz (fast)
            p_CLKOUT1_PHASE   = 0.0,
            p_CLKOUT1_DUTY_CYCLE = 0.5,

            i_CLKIN1   = clk25.i,
            i_CLKFBIN  = mainpll_feedback,
            o_CLKFBOUT = mainpll_feedback,
            o_CLKOUT0  = sys_clk,
            o_CLKOUT1  = fast_clk,
            o_LOCKED   = sys_locked,
        )

        # USB-PLL: take ULPI CLK input (60 MHz from PHY) and re-emit
        # 60 MHz with a phase shift. Mirrors LiteX terasic_deca _CRG
        # pattern (validated with LUNA): pll.create_clkout(usb, 60e6,
        # phase=-120). The phase shift aligns the FPGA's sampling
        # edge inside the ULPI data valid window — without it, the
        # LUNA register-window FSM exits IDLE briefly but never
        # completes a write because the data sampled by IOB flops is
        # past its valid window.
        #
        # PLLE2_ADV constraints: VCO 800-1600 MHz on Artix-7 -1 speed.
        # Use CLKFBOUT_MULT=16 (VCO = 60 × 16 = 960 MHz), CLKOUT0_DIVIDE=16
        # (60 MHz out), CLKOUT0_PHASE=-120.
        usbpll_feedback = Signal()
        usb_clk_pll     = Signal()
        usb_pll_locked  = Signal()
        m.submodules.usbpll = Instance("PLLE2_ADV",
            p_BANDWIDTH         = "OPTIMIZED",
            p_COMPENSATION      = "INTERNAL",
            p_STARTUP_WAIT      = "FALSE",
            p_DIVCLK_DIVIDE     = 1,
            p_CLKFBOUT_MULT     = 16,
            p_CLKFBOUT_PHASE    = 0.0,
            p_CLKIN1_PERIOD     = 16.667,        # 60 MHz period
            p_CLKOUT0_DIVIDE    = 16,
            p_CLKOUT0_PHASE     = self.usb_phase,
            p_CLKOUT0_DUTY_CYCLE= 0.5,
            i_CLKIN1   = self.ulpi_clk_pin,
            i_CLKFBIN  = usbpll_feedback,
            o_CLKFBOUT = usbpll_feedback,
            o_CLKOUT0  = usb_clk_pll,
            o_LOCKED   = usb_pll_locked,
        )

        m.d.comb += [
            cd_sync.clk.eq(sys_clk),
            cd_fast.clk.eq(fast_clk),
            cd_usb.clk .eq(usb_clk_pll),
        ]

        # Until PLL is locked, hold sync/fast in reset. The usb domain
        # comes up when the PHY enables itself.
        reset = ~sys_locked
        m.submodules.reset_sync_sync = ResetSynchronizer(reset, domain="sync")
        m.submodules.reset_sync_fast = ResetSynchronizer(reset, domain="fast")

        return m
